### ISSUE TITLE
Differences between proposed API and current implementation

### ISSUE THREAD

**Issue by mwcraig** [eteq/astrowidgets#10]
These differences are mostly name differences and in most cases the current names are, I think, fine.  

ping @eteq 

(Edit by @eteq: the proposed API in question is here: https://gist.github.com/eteq/bb625148969db51b2b03b71e92ca5231)

| Proposed API | Current Implementation |
| ------------ | ----------- |
| `reset_marks()` | `reset_markers()` |
| `add_marks()` | `add_markers()` |
| `is_selecting`  | `is_marking` |
| `stop_selecting(clear_marks=True)` | `stop_marking(clear_markers=True)` |
| `get_selection()` | `get_markers()` |
| `select_points()` | **Not Implemented** but can set `is_marking` |
| `zoom` and `zoom_level` | See issue #9  |

**Comment by pllim** [comment]
API change for markers was done consciously and I explained my thought process over at #1. I am open to renaming. Please let me know.

The zoom stuff happened earlier when I subclassesed directly from Ginga widget, and had to rename to avoid name clash, and then didn't change things back after I undid the subclassing. So it was semi-accidental. Also open to changing it back if you want.

**Comment by mwcraig** [comment]
I agree with all of the changes you’ve made; selecting becomes particularly ambiguous once there are options like line or box selections.

**Comment by eteq** [comment]
I think these all look fine *except* `select_points`. Re: `select_points`, I don't quite agree think that's better discussed elsewhere.  I should have mentioned it in #1 (my bad) but since that's merged now I'll move the discussion to a new issue.

Since it looks like @mwcraig and I are ok with it aside from that and #9, I think this can be closed once I've made the new issue.

**Comment by eteq** [comment]
See #16 for my thinking on the markers.  I think with that I can close this since these have all been 👍 'd or have their own issues
